//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Space.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Space.Language.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Best date for launching&quot;.
        /// </summary>
        internal static string BestDayLaunching {
            get {
                return ResourceManager.GetString("BestDayLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best date for launching is :.
        /// </summary>
        internal static string BestLaunchingDate {
            get {
                return ResourceManager.GetString("BestLaunchingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best Spaceport for launching is: {0} on {1}..
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email. Please verify your credentials and try again..
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather condition analysis for launching to SPACE.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your e-mail..
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the path to the folder where you are storing the CSV files!.
        /// </summary>
        internal static string EnterFolderPath {
            get {
                return ResourceManager.GetString("EnterFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your e-mail password..
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the receiver email..
        /// </summary>
        internal static string EnterReceiverEmail {
            get {
                return ResourceManager.GetString("EnterReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, dear user!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter in &apos;{0}&apos;. Please, check!.
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clouds data is missing for {0} July!.
        /// </summary>
        internal static string MissingCloudData {
            get {
                return ResourceManager.GetString("MissingCloudData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something in &apos;{0}&apos;.csv is wrong! Check for missing information(empty cells)..
        /// </summary>
        internal static string MissingCSVFileData {
            get {
                return ResourceManager.GetString("MissingCSVFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but it looks like there is no csv files in this folder..
        /// </summary>
        internal static string MissingCSVFiles {
            get {
                return ResourceManager.GetString("MissingCSVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this folder does not exist! PLease, try with another one..
        /// </summary>
        internal static string MissingFolder {
            get {
                return ResourceManager.GetString("MissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity data is missing for {0} July!.
        /// </summary>
        internal static string MissingHumidityData {
            get {
                return ResourceManager.GetString("MissingHumidityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but it looks like you missed to enter something..
        /// </summary>
        internal static string MissingInput {
            get {
                return ResourceManager.GetString("MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning data is missing for {0} July!.
        /// </summary>
        internal static string MissingLightning {
            get {
                return ResourceManager.GetString("MissingLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation data is missing for {0} July!.
        /// </summary>
        internal static string MissingPrecipitationData {
            get {
                return ResourceManager.GetString("MissingPrecipitationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no suitable date for this location..
        /// </summary>
        internal static string MissingSuitableDate {
            get {
                return ResourceManager.GetString("MissingSuitableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature data is missing for {i} July!.
        /// </summary>
        internal static string MissingTemperatureData {
            get {
                return ResourceManager.GetString("MissingTemperatureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind data is missing for {i} July!.
        /// </summary>
        internal static string MissingWindData {
            get {
                return ResourceManager.GetString("MissingWindData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  July.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, no! It seems like there is a problem with file reading..
        /// </summary>
        internal static string ReadingError {
            get {
                return ResourceManager.GetString("ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating analysis report failed!.
        /// </summary>
        internal static string ReportNotSaved {
            get {
                return ResourceManager.GetString("ReportNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis report has been successfully saved to &apos;LaunchAnalysisReport.csv&apos;..
        /// </summary>
        internal static string ReportSaved {
            get {
                return ResourceManager.GetString("ReportSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Spaceport Location&quot;.
        /// </summary>
        internal static string SpaceportLocation {
            get {
                return ResourceManager.GetString("SpaceportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this program!.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
    }
}
